Chrome_driver_path = "D:\CODING STUFF\CHROMEDRIVER_103\chromedriver.exe"
demoblaze_url = "https://www.demoblaze.com/"
product_Icon = "xpath:(//a[@class='navbar-brand']//img[@src='bm.png'])"
product_One = "xpath:(//a[contains(text(),'Samsung galaxy s7')])"
cart_Button = "xpath:(//a[contains(text(),'Add to cart')])"
cart_Icon = "xpath:((//ul[@class='navbar-nav ml-auto']//li[@class='nav-item'])[3]//a[contains(text(),'Cart')])"
product_One_Icon = "xpath:(//tbody[@id='tbodyid']//following-sibling::td[contains(text(),'Samsung')])"
place_Order_Button = "xpath:(//button[contains(text(),'Place Order')])"
place_Order_Name = "xpath:(//div[@class='form-group']//input[@id='name'])"
place_Order_Country = "xpath:(//div[@class='form-group']//input[@id='country'])"
place_Order_City = "xpath:(//div[@class='form-group']//input[@id='city'])"
place_Order_Credit = "xpath:(//div[@class='form-group']//input[@id='card'])"
place_Order_Month = "xpath:(//div[@class='form-group']//input[@id='month'])"
place_Order_Year = "xpath:(//div[@class='form-group']//input[@id='year'])"
purchase_Button = "xpath:(//button[contains(text(),'Purchase')])"
confirm_Message = "xpath:(//h2[contains(text(),'Thank you for your purchase')])"